Feature/style
Aseadd/bookstore-app pull request #6
Opened 2022-09-22 20:42 UTC by Aseadd

### **Hello, Good Reviewer 👋** 

### **Tasks are done for the exercise**

- [ ] No linter error ✔️ 
- [ ] Gitflow configured well ✔️ 
- [ ] Apply best practices for JS and CSS ✔️ 
- [ ] Add Style for the App ✔️ 
- [ ] Style meet Zeplin design ✔️ 

<img src="https://media1.giphy.com/media/E1w0yvMxBIv5M8WkL8/giphy.gif"/>

![book1](https://user-images.githubusercontent.com/48018471/191826967-6fb56a37-02eb-4945-aed1-2641eefe66b6.PNG)
![book2](https://user-images.githubusercontent.com/48018471/191826970-95611ae4-5062-411a-95e7-a213592255e0.PNG)

2022-09-22 22:28 UTC, BenMukebo requested changes
### Hi @Aseadd,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Good commit messages ✔️ 
- Professional README ✔️ 
- You have followed  JavaScript best practices. ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 22:28 UTC, BenMukebo commented on src/components/styles.css
> +  text-align: center;
- [ ] Great job so far 👏🏻 However the Styling must be EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/). kindly change the background-color of your navbar, footer, and main page, ... to match the original design. Make sure the main page is aligned in the center, you need to fix the margin-left and margin-right and you need to add the missing part 👍🏻 

- Your Design:

![18](https://user-images.githubusercontent.com/79058364/191857527-7b5fb695-a663-4b21-b1ea-4d7c617cfc55.png)

- Original Design:

![image](https://user-images.githubusercontent.com/79058364/191857667-6f501420-6d4a-41ab-a615-f0829889a246.png)

2022-09-23 00:18 UTC, AmaduKamara requested changes
## Status: Requires Changes ♻️♻️♻️ 

Hi @Aseadd,

Good job so far on making the changes requested by the previous reviewer! 👍
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅  You used Gitflow correctly
✅ No linter error
✅ Good descriptive PR
✅ Your README is good
✅ App features work fine 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-23 00:18 UTC, AmaduKamara commented on src/components/styles.css
>  }
- [ ] Kindly justify the contents of the navbar to the center so your header style matches the original design just as the previous reviewer highlighted.

Hint:
Add this style to this nav-bar class `justify-content: center;` and things will be perfect as required 👍 

**Your Styles**
![image](https://user-images.githubusercontent.com/50941074/191872052-827bee91-ac2d-4fda-9fe7-9682fc99c869.png)

**The original design**
![image](https://user-images.githubusercontent.com/50941074/191872116-ec9adc76-2631-41f1-ae99-c3522b5bc679.png)

2022-09-23 16:06 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 16:09 UTC, merged